package com.doerit.model;

public class Action {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.age
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.other
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.age
     *
     * @return the value of tbl_user.age
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.age
     *
     * @param age the value for tbl_user.age
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.other
     *
     * @return the value of tbl_user.other
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.other
     *
     * @param other the value for tbl_user.other
     *
     * @mbg.generated Fri Dec 01 04:20:01 IST 2017
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}